Slope Percentage Overlay v1
muxable/rtirl-obs pull request #147
Opened 2022-07-15 22:37 UTC by sprEEEzy

Initial version, needs testing! Works best with 10/100 meter updates.

2022-07-15 22:39 UTC, kevmo314 commented
@juaoose or @chungwwei can you review and also once it gets in add it to the gallery? :)

2022-07-16 00:12 UTC, juaoose requested changes

2022-07-16 00:12 UTC, juaoose commented on public/inclination/slope.html
> +      var unit = '%';
Probably better if we leave this constant in the .js file so that its clear right away.

2022-07-16 00:12 UTC, juaoose commented on public/inclination/inclination.js
> +        //document.getElementById("text").innerText = JSON.stringify(data);
```suggestion
```

2022-07-18 12:25 UTC, juaoose approved these changes

2022-07-18 12:25 UTC, merged