fix: add keys to list elements to remove warning
muxable/rtirl-obs pull request #60
Opened 2022-05-31 22:28 UTC by juaoose

2022-05-31 23:46 UTC, kevmo314 requested changes

2022-05-31 23:46 UTC, kevmo314 commented on web-editor/src/component/CountryPicker.tsx
> +        <MenuItem value={country} key={index}>
```suggestion
        <MenuItem value={country} key={country}>
```

2022-05-31 23:46 UTC, kevmo314 commented on web-editor/src/component/CountryPicker.tsx
> +        <MenuItem value={country} key={index}>
It would be better to make the country the key. If the index is the key, the child has to rerender anyways because the content changes.

2022-05-31 23:46 UTC, kevmo314 commented on web-editor/src/component/NavigationDrawer.jsx
> +              key={index}
Same here, `action.name` should be the key.

2022-06-01 08:19 UTC, chungwwei approved these changes

2022-06-01 19:59 UTC, kevmo314 approved these changes

2022-06-01 19:59 UTC, merged